// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.15.8
// source: api/v1/msg.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendUserMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"sender_id" form:"sender_id" uri:"sender_id"
	SenderId string `protobuf:"bytes,1,opt,name=SenderId,proto3" json:"sender_id" form:"sender_id" uri:"sender_id"`
	// @inject_tag: json:"receiver_id" form:"receiver_id" uri:"receiver_id"
	ReceiverId string `protobuf:"bytes,2,opt,name=ReceiverId,proto3" json:"receiver_id" form:"receiver_id" uri:"receiver_id"`
	// @inject_tag: json:"content" form:"content" uri:"content"
	Content string `protobuf:"bytes,3,opt,name=Content,proto3" json:"content" form:"content" uri:"content"`
	// @inject_tag: json:"type" form:"type" uri:"type"
	Type int32 `protobuf:"varint,4,opt,name=Type,proto3" json:"type" form:"type" uri:"type"`
	// @inject_tag: json:"replay_id" form:"replay_id" uri:"replay_id"
	ReplayId uint64 `protobuf:"varint,5,opt,name=ReplayId,proto3" json:"replay_id" form:"replay_id" uri:"replay_id"`
}

func (x *SendUserMsgRequest) Reset() {
	*x = SendUserMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendUserMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserMsgRequest) ProtoMessage() {}

func (x *SendUserMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserMsgRequest.ProtoReflect.Descriptor instead.
func (*SendUserMsgRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_msg_proto_rawDescGZIP(), []int{0}
}

func (x *SendUserMsgRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendUserMsgRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *SendUserMsgRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendUserMsgRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SendUserMsgRequest) GetReplayId() uint64 {
	if x != nil {
		return x.ReplayId
	}
	return 0
}

type SendGroupMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"user_id" form:"user_id" uri:"user_id"
	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"user_id" form:"user_id" uri:"user_id"`
	// @inject_tag: json:"group_id" form:"group_id" uri:"group_id"
	GroupId string `protobuf:"bytes,2,opt,name=GroupId,proto3" json:"group_id" form:"group_id" uri:"group_id"`
	// @inject_tag: json:"content" form:"content" uri:"content"
	Content string `protobuf:"bytes,3,opt,name=Content,proto3" json:"content" form:"content" uri:"content"`
	// @inject_tag: json:"type" form:"type" uri:"type"
	Type int32 `protobuf:"varint,4,opt,name=Type,proto3" json:"type" form:"type" uri:"type"`
	// @inject_tag: json:"replay_id" form:"replay_id" uri:"replay_id"
	ReplayId uint64 `protobuf:"varint,5,opt,name=ReplayId,proto3" json:"replay_id" form:"replay_id" uri:"replay_id"`
}

func (x *SendGroupMsgRequest) Reset() {
	*x = SendGroupMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGroupMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMsgRequest) ProtoMessage() {}

func (x *SendGroupMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMsgRequest.ProtoReflect.Descriptor instead.
func (*SendGroupMsgRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_msg_proto_rawDescGZIP(), []int{1}
}

func (x *SendGroupMsgRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendGroupMsgRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SendGroupMsgRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendGroupMsgRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SendGroupMsgRequest) GetReplayId() uint64 {
	if x != nil {
		return x.ReplayId
	}
	return 0
}

type SendUserMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendUserMsgResponse) Reset() {
	*x = SendUserMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendUserMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserMsgResponse) ProtoMessage() {}

func (x *SendUserMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserMsgResponse.ProtoReflect.Descriptor instead.
func (*SendUserMsgResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_msg_proto_rawDescGZIP(), []int{2}
}

type SendGroupMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"user_ids" form:"user_ids" uri:"user_ids"
	UserIds []string `protobuf:"bytes,1,rep,name=UserIds,proto3" json:"user_ids" form:"user_ids" uri:"user_ids"`
}

func (x *SendGroupMsgResponse) Reset() {
	*x = SendGroupMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGroupMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMsgResponse) ProtoMessage() {}

func (x *SendGroupMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMsgResponse.ProtoReflect.Descriptor instead.
func (*SendGroupMsgResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_msg_proto_rawDescGZIP(), []int{3}
}

func (x *SendGroupMsgResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_api_v1_msg_proto protoreflect.FileDescriptor

var file_api_v1_msg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0x9a, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6c, 0x61,
	0x79, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6c, 0x61,
	0x79, 0x49, 0x64, 0x22, 0x91, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52,
	0x65, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x52,
	0x65, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30,
	0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73,
	0x32, 0x97, 0x01, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x42, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x73, 0x69, 0x6d, 0x2f,
	0x63, 0x6f, 0x73, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_msg_proto_rawDescOnce sync.Once
	file_api_v1_msg_proto_rawDescData = file_api_v1_msg_proto_rawDesc
)

func file_api_v1_msg_proto_rawDescGZIP() []byte {
	file_api_v1_msg_proto_rawDescOnce.Do(func() {
		file_api_v1_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_msg_proto_rawDescData)
	})
	return file_api_v1_msg_proto_rawDescData
}

var file_api_v1_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_msg_proto_goTypes = []interface{}{
	(*SendUserMsgRequest)(nil),   // 0: v1.SendUserMsgRequest
	(*SendGroupMsgRequest)(nil),  // 1: v1.SendGroupMsgRequest
	(*SendUserMsgResponse)(nil),  // 2: v1.SendUserMsgResponse
	(*SendGroupMsgResponse)(nil), // 3: v1.SendGroupMsgResponse
}
var file_api_v1_msg_proto_depIdxs = []int32{
	0, // 0: v1.MsgService.SendUserMessage:input_type -> v1.SendUserMsgRequest
	1, // 1: v1.MsgService.SendGroupMessage:input_type -> v1.SendGroupMsgRequest
	2, // 2: v1.MsgService.SendUserMessage:output_type -> v1.SendUserMsgResponse
	3, // 3: v1.MsgService.SendGroupMessage:output_type -> v1.SendGroupMsgResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_msg_proto_init() }
func file_api_v1_msg_proto_init() {
	if File_api_v1_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendUserMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGroupMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendUserMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGroupMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_msg_proto_goTypes,
		DependencyIndexes: file_api_v1_msg_proto_depIdxs,
		MessageInfos:      file_api_v1_msg_proto_msgTypes,
	}.Build()
	File_api_v1_msg_proto = out.File
	file_api_v1_msg_proto_rawDesc = nil
	file_api_v1_msg_proto_goTypes = nil
	file_api_v1_msg_proto_depIdxs = nil
}
