// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: api/v1/user_friend_requests.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendRequestStatus int32

const (
	// 申请中
	FriendRequestStatus_FriendRequestStatus_PENDING FriendRequestStatus = 0
	// 已同意
	FriendRequestStatus_FriendRequestStatus_ACCEPT FriendRequestStatus = 1
	// 已拒绝
	FriendRequestStatus_FriendRequestStatus_REJECT FriendRequestStatus = 2
)

// Enum value maps for FriendRequestStatus.
var (
	FriendRequestStatus_name = map[int32]string{
		0: "FriendRequestStatus_PENDING",
		1: "FriendRequestStatus_ACCEPT",
		2: "FriendRequestStatus_REJECT",
	}
	FriendRequestStatus_value = map[string]int32{
		"FriendRequestStatus_PENDING": 0,
		"FriendRequestStatus_ACCEPT":  1,
		"FriendRequestStatus_REJECT":  2,
	}
)

func (x FriendRequestStatus) Enum() *FriendRequestStatus {
	p := new(FriendRequestStatus)
	*p = x
	return p
}

func (x FriendRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_user_friend_requests_proto_enumTypes[0].Descriptor()
}

func (FriendRequestStatus) Type() protoreflect.EnumType {
	return &file_api_v1_user_friend_requests_proto_enumTypes[0]
}

func (x FriendRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendRequestStatus.Descriptor instead.
func (FriendRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_user_friend_requests_proto_rawDescGZIP(), []int{0}
}

type GetFriendRequestListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"user_id"
	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"user_id"`
}

func (x *GetFriendRequestListRequest) Reset() {
	*x = GetFriendRequestListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_user_friend_requests_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendRequestListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestListRequest) ProtoMessage() {}

func (x *GetFriendRequestListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_friend_requests_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestListRequest.ProtoReflect.Descriptor instead.
func (*GetFriendRequestListRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_friend_requests_proto_rawDescGZIP(), []int{0}
}

func (x *GetFriendRequestListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFriendRequestListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"friend_request_list"
	FriendRequestList []*FriendRequestList `protobuf:"bytes,1,rep,name=FriendRequestList,proto3" json:"friend_request_list"`
}

func (x *GetFriendRequestListResponse) Reset() {
	*x = GetFriendRequestListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_user_friend_requests_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendRequestListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestListResponse) ProtoMessage() {}

func (x *GetFriendRequestListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_friend_requests_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestListResponse.ProtoReflect.Descriptor instead.
func (*GetFriendRequestListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_user_friend_requests_proto_rawDescGZIP(), []int{1}
}

func (x *GetFriendRequestListResponse) GetFriendRequestList() []*FriendRequestList {
	if x != nil {
		return x.FriendRequestList
	}
	return nil
}

type FriendRequestList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	// @inject_tag: json:"sender_id"
	SenderId string `protobuf:"bytes,2,opt,name=SenderId,proto3" json:"sender_id"` // 发送方id
	// @inject_tag: json:"receiver_id"
	ReceiverId string `protobuf:"bytes,3,opt,name=ReceiverId,proto3" json:"receiver_id"` // 接收方id
	// @inject_tag: json:"status"
	Status FriendRequestStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=v1.FriendRequestStatus" json:"status"` //状态
	// @inject_tag: json:"remark"
	Remark string `protobuf:"bytes,5,opt,name=Remark,proto3" json:"remark"` //备注
	// @inject_tag: json:"create_at"
	CreateAt uint64 `protobuf:"varint,6,opt,name=CreateAt,proto3" json:"create_at"`
}

func (x *FriendRequestList) Reset() {
	*x = FriendRequestList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_user_friend_requests_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestList) ProtoMessage() {}

func (x *FriendRequestList) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_friend_requests_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestList.ProtoReflect.Descriptor instead.
func (*FriendRequestList) Descriptor() ([]byte, []int) {
	return file_api_v1_user_friend_requests_proto_rawDescGZIP(), []int{2}
}

func (x *FriendRequestList) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *FriendRequestList) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *FriendRequestList) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *FriendRequestList) GetStatus() FriendRequestStatus {
	if x != nil {
		return x.Status
	}
	return FriendRequestStatus_FriendRequestStatus_PENDING
}

func (x *FriendRequestList) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FriendRequestList) GetCreateAt() uint64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

type SendFriendRequestStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"sender_id"
	SenderId string `protobuf:"bytes,1,opt,name=SenderId,proto3" json:"sender_id"` // 发送请求方id
	// @inject_tag: json:"receiver_id"
	ReceiverId string `protobuf:"bytes,2,opt,name=ReceiverId,proto3" json:"receiver_id"` // 接收请求方id
	// @inject_tag: json:"remark"
	Remark string `protobuf:"bytes,3,opt,name=Remark,proto3" json:"remark"` // 申请信息
}

func (x *SendFriendRequestStruct) Reset() {
	*x = SendFriendRequestStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_user_friend_requests_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendRequestStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestStruct) ProtoMessage() {}

func (x *SendFriendRequestStruct) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_friend_requests_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestStruct.ProtoReflect.Descriptor instead.
func (*SendFriendRequestStruct) Descriptor() ([]byte, []int) {
	return file_api_v1_user_friend_requests_proto_rawDescGZIP(), []int{3}
}

func (x *SendFriendRequestStruct) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendFriendRequestStruct) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *SendFriendRequestStruct) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ManageFriendRequestStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	// @inject_tag: json:"status"
	Status FriendRequestStatus `protobuf:"varint,3,opt,name=Status,proto3,enum=v1.FriendRequestStatus" json:"status"`
}

func (x *ManageFriendRequestStruct) Reset() {
	*x = ManageFriendRequestStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_user_friend_requests_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManageFriendRequestStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageFriendRequestStruct) ProtoMessage() {}

func (x *ManageFriendRequestStruct) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_friend_requests_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageFriendRequestStruct.ProtoReflect.Descriptor instead.
func (*ManageFriendRequestStruct) Descriptor() ([]byte, []int) {
	return file_api_v1_user_friend_requests_proto_rawDescGZIP(), []int{4}
}

func (x *ManageFriendRequestStruct) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ManageFriendRequestStruct) GetStatus() FriendRequestStatus {
	if x != nil {
		return x.Status
	}
	return FriendRequestStatus_FriendRequestStatus_PENDING
}

var File_api_v1_user_friend_requests_proto protoreflect.FileDescriptor

var file_api_v1_user_friend_requests_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x1c, 0x47,
	0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x11, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x11, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0xc4, 0x01, 0x0a, 0x11, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x6d, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x5c, 0x0a, 0x19, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2a, 0x76, 0x0a, 0x13, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x02, 0x32, 0x8d, 0x02, 0x0a,
	0x18, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4c,
	0x0a, 0x13, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x37, 0x5a, 0x35,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x73, 0x69,
	0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_user_friend_requests_proto_rawDescOnce sync.Once
	file_api_v1_user_friend_requests_proto_rawDescData = file_api_v1_user_friend_requests_proto_rawDesc
)

func file_api_v1_user_friend_requests_proto_rawDescGZIP() []byte {
	file_api_v1_user_friend_requests_proto_rawDescOnce.Do(func() {
		file_api_v1_user_friend_requests_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_user_friend_requests_proto_rawDescData)
	})
	return file_api_v1_user_friend_requests_proto_rawDescData
}

var file_api_v1_user_friend_requests_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_user_friend_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_user_friend_requests_proto_goTypes = []interface{}{
	(FriendRequestStatus)(0),             // 0: v1.FriendRequestStatus
	(*GetFriendRequestListRequest)(nil),  // 1: v1.GetFriendRequestListRequest
	(*GetFriendRequestListResponse)(nil), // 2: v1.GetFriendRequestListResponse
	(*FriendRequestList)(nil),            // 3: v1.FriendRequestList
	(*SendFriendRequestStruct)(nil),      // 4: v1.SendFriendRequestStruct
	(*ManageFriendRequestStruct)(nil),    // 5: v1.ManageFriendRequestStruct
	(*emptypb.Empty)(nil),                // 6: google.protobuf.Empty
}
var file_api_v1_user_friend_requests_proto_depIdxs = []int32{
	3, // 0: v1.GetFriendRequestListResponse.FriendRequestList:type_name -> v1.FriendRequestList
	0, // 1: v1.FriendRequestList.Status:type_name -> v1.FriendRequestStatus
	0, // 2: v1.ManageFriendRequestStruct.Status:type_name -> v1.FriendRequestStatus
	1, // 3: v1.UserFriendRequestService.GetFriendRequestList:input_type -> v1.GetFriendRequestListRequest
	4, // 4: v1.UserFriendRequestService.SendFriendRequest:input_type -> v1.SendFriendRequestStruct
	5, // 5: v1.UserFriendRequestService.ManageFriendRequest:input_type -> v1.ManageFriendRequestStruct
	2, // 6: v1.UserFriendRequestService.GetFriendRequestList:output_type -> v1.GetFriendRequestListResponse
	6, // 7: v1.UserFriendRequestService.SendFriendRequest:output_type -> google.protobuf.Empty
	6, // 8: v1.UserFriendRequestService.ManageFriendRequest:output_type -> google.protobuf.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_user_friend_requests_proto_init() }
func file_api_v1_user_friend_requests_proto_init() {
	if File_api_v1_user_friend_requests_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_user_friend_requests_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendRequestListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_user_friend_requests_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendRequestListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_user_friend_requests_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendRequestList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_user_friend_requests_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFriendRequestStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_user_friend_requests_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManageFriendRequestStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_user_friend_requests_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_user_friend_requests_proto_goTypes,
		DependencyIndexes: file_api_v1_user_friend_requests_proto_depIdxs,
		EnumInfos:         file_api_v1_user_friend_requests_proto_enumTypes,
		MessageInfos:      file_api_v1_user_friend_requests_proto_msgTypes,
	}.Build()
	File_api_v1_user_friend_requests_proto = out.File
	file_api_v1_user_friend_requests_proto_rawDesc = nil
	file_api_v1_user_friend_requests_proto_goTypes = nil
	file_api_v1_user_friend_requests_proto_depIdxs = nil
}
